# Generated by Django 4.2.2 on 2025-02-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(help_text='Введите наименование', max_length=150, verbose_name='Наименование')),
                (
                'description', models.CharField(
                    help_text='Введите описание',
                    max_length=200,
                    verbose_name='Описание'
                )
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(help_text='Введите наименование', max_length=100, verbose_name='Наименование')),
                (
                'description', models.CharField(help_text='Введите описание', max_length=100, verbose_name='Описание')
                ),
                ('image',
                 models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='Product/photo',
                                   verbose_name='Фото')),
                ('price',
                 models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену продукта', max_digits=10,
                                     null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Укажите дату создания', null=True,
                                                    verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего изменения', null=True,
                                                    verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию', null=True,
                                               on_delete=django.db.models.deletion.SET_NULL, related_name='products',
                                               to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['description', 'category', 'price', 'created_at', 'updated_at'],
            },
        ),
    ]
