# Generated by Django 5.1.5 on 2025-01-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "description",
                    "category",
                    "price",
                    "created_at",
                    "updated_at",
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="purchase_price",
            new_name="price",
        ),
    ]
