# Generated by Django 4.2.2 on 2025-02-18 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['description', 'category', 'price', 'created_at', 'updated_at', 'owner'],
                     'permissions': [('can_unpublish_product', 'can unpublish product')], 'verbose_name': 'Продукт',
                     'verbose_name_plural': 'Продукты'},
        ),
    ]
