# Generated by Django 4.2.2 on 2025-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_views_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать продукт?'),
        ),
    ]
